### PR TITLE
Revert "*: remove expression index out of experimental feature."

### PR DESCRIPTION
**Pull request by wjhuang2016**
Reverts pingcap/docs-cn#4641

Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- Other reference link(s):https://github.com/pingcap/tidb/pull/19998

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by TomShawn** [comment]
Why reverting https://github.com/pingcap/docs-cn/pull/4641?

**Review by djshow832 — COMMENTED** [review]
LGTM

**Comment by wjhuang2016** [comment]
> Why reverting #4641?

Expression index is not GA in sprint1.

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
