### PR TITLE
ticdc: revert cdc ga

### PR DESCRIPTION
**Pull request by amyangfei**
### What is changed, added or deleted? (Required)

revert 1b01988b9e2f81edf96f83c33ff09f5f68b89823, cdc ga is delayed two weeks

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by amyangfei** [comment]
PTAL @overvenus @TomShawn

**Review by TomShawn — APPROVED** [review]
LGTM

**Review by leoppro — COMMENTED** [review]
LGTM

**Pull request merged**
