### PR TITLE
Remove --log

### PR DESCRIPTION
**Pull request by glkappe**
--log is not supported in the v4 version. Our command line parameter documentation should be checked carefully. The use of `--` and `-` is not consistent with that shown in ./tidb-server -V

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by glkappe** [comment]
[root@172 bin]# ./tidb-server -V
**Release Version: v4.0.6**
Edition: Community
Git Commit Hash: 51d365fc45fdfc039eb204a96268c5bd1c55075f
Git Branch: heads/refs/tags/v4.0.6
UTC Build Time: 2020-09-15 09:50:30
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

[root@172 bin]# ./tidb-server --log error
**flag provided but not defined: -log**

**Comment by glkappe** [comment]
Please do a technical review

**Comment by TomShawn** [comment]
@sticnarf 请测试评估下，其他版本是否也有相同的问题，谢谢！

**Comment by glkappe** [comment]
补充一个 v5.0.1 的测试结果
[tidb@node4107 bin]$ ./tidb-server -V
**Release Version: v5.0.1**
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
[tidb@node4107 bin]$ ./tidb-server --log error
**flag provided but not defined: -log**


v3.0.12 测试结果
[tidb@node4107 v3.0.12]$ ./tidb-server -V
**Release Version: v3.0.12**
Git Commit Hash: 8c4696b3f3408c61dd7454204ddd67c93501609a
Git Branch: heads/refs/tags/v3.0.12
UTC Build Time: 2020-03-16 09:56:22
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
[tidb@node4107 v3.0.12]$ ./tidb-server --log error
**flag provided but not defined: -log**
Usage of ./tidb-server:

**Review by sticnarf — APPROVED** [review]
LGTM

**Pull request merged**
