### PR TITLE
Update tidb-lightning-overview.md

### PR DESCRIPTION
**Pull request by xxj123go**
### What is changed, added or deleted? (Required)
Correction of ambiguity in expression

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version) https://github.com/pingcap/docs-cn/pull/4384
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by TomShawn** [comment]
@xxj123go Thanks for your contribution. Would you sign the [CLA](https://cla-assistant.io/pingcap/docs-cn?pullRequest=4372) for this PR to merge?

**Review by TomShawn — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by xxj123go** [comment]
> @xxj123go Thanks for your contribution. Would you sign the [CLA](https://cla-assistant.io/pingcap/docs-cn?pullRequest=4372) for this PR to merge?
signed already

**Pull request merged**
