### PR TITLE
Fix typo in literal values

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? (Required)

Fix typo in literal values

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/3236

### CODE REVIEW

**Comment by ran-huang** [comment]
@TomShawn LGTM.
Please don't merge it yet. I'll fix other typos in this PR.

**Comment by ran-huang** [comment]
@TomShawn PTAL at this commit https://github.com/pingcap/docs-cn/pull/3845/commits/624966b7fdedfda06750fecc6d6a5bb86337f4bc. Thanks~

**Comment by TomShawn** [comment]
> @TomShawn PTAL at this commit [624966b](https://github.com/pingcap/docs-cn/commit/624966b7fdedfda06750fecc6d6a5bb86337f4bc). Thanks~

LGTM

**Pull request merged**
