### PR TITLE
Adjust the readme file

### PR DESCRIPTION
**Pull request by queenypingcap**
I commented the docs that haven't been added.

### CODE REVIEW

**Comment by queenypingcap** [comment]
@andelf @xuechunL PTAL.

**Comment by xuechunL** [comment]
before '快速入门指南(QUICKSTART.md)' item should use ' + '

**Comment by andelf** [comment]
Reset LGTM

Both website generating & pdf generating are now yet prepared for level-3 TOC.

**Comment by andelf** [comment]
Seem that you've revert some changes? like `op-guide/requirement.md`

**Comment by xuechunL** [comment]
LGTM

**Comment by andelf** [comment]
LGTM

**Pull request merged**
