### PR TITLE
remove useless variable.

### PR DESCRIPTION
**Pull request by LittleFall**
### What is changed, added or deleted? (Required)

This variable is deprecated and useless when mpp is enabled, but may confuse users, so I remove it.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
@LittleFall could you refer to the issue in description or comment where we drop bcj for MPP?

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by LittleFall** [comment]
> @LittleFall could you refer to the issue in description or comment where we drop bcj for MPP?


yeah, according to https://github.com/pingcap/tidb/blob/v5.0.0/planner/core/exhaust_physical_plans.go#L1662-L1679, when mpp is allowed, we will never use old BCJ.

**Review by tisonkun — APPROVED** [review]
LGTM.

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
