### PR TITLE
reference: update the schema information of slow-query table

### PR DESCRIPTION
**Pull request by zz-jason**
### What is changed, added or deleted? 

The schema of the current slow-query table is outdated, this PR updates it.

### Which version does your change affect? 

v3.0

### Checklist 

- [x] Add a new file to `TOC.md`
- [x] No Tab spaces anywhere 
- [x] Leave a blank line both before and after a code block
- [x] Keep the first level heading consistent with `title` in metadata
- [x] Use *four* spaces for each level of indentation except that in `TOC.md`

### CODE REVIEW

**Comment by lilin90** [comment]
@zz-jason Please confirm whether your changes apply to `dev` and `v2.1`, and update accordingly. Thanks!

**Comment by zz-jason** [comment]
@lilin90 release-2.1 also has this table, we need to cherry pick this to 2.1

**Comment by lilin90** [comment]
@zz-jason You can directly update `docs-cn/v2.1/...` in this PR.

**Comment by zz-jason** [comment]
@lichunzhu 2.1/3.0/dev branches are all updated, PTAL

**Pull request merged**
