### PR TITLE
reference/sql: update generate column document

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What is the related PR or file link(s)? 

- [x] Reference link(s):pingcap/tidb#12407
- [ ] This PR is to align with:
- [ ] N/A (not applicable)

### Which TiDB version(s) does your changes apply to? 

- [ ] All active versions: dev, v3.0, v2.1, v3.1
- [x] dev (the latest development version)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] All active and inactive versions
- [ ] N/A (not applicable)

**Note:** If your changes apply to multiple TiDB versions, make sure you update the documents in the **corresponding** version folders such as "dev", "v3.0", "v2.1" and "v3.1" in this PR.

- [ ] Updated one version first. Will update other versions after I get two LGTMs.

### CODE REVIEW

**Comment by wjhuang2016** [comment]
@TomShawn PTAL

**Comment by TomShawn** [comment]
Could you update the example to a VIRTUAL column as mentioned in https://github.com/pingcap/docs/issues/1767 ?

**Comment by wjhuang2016** [comment]
> Could you update the example to a VIRTUAL column as mentioned in [pingcap/docs#1767](https://github.com/pingcap/docs/issues/1767)?

If we update the example as mentioned in the issue, the document's logic will be poor.
I think the document needs to be completely rewritten，which will take some time to complete.

**Comment by TomShawn** [comment]
LGTM

**Pull request merged**
