### PR TITLE
Fix bug in quick-start-with-tidb.md 

### PR DESCRIPTION
**Pull request by asddongmen**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
 Fix a bug in quick-start-with-tidb.md  
 The old version command to restart a ssh servcice is `service sshd restart` , it's wrong.
 I have changed it to a correct one ` service ssh restart `.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [x] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@King-Dylan PTAL and confirm whether any other version also needs this change. Thanks~

**Comment by King-Dylan** [comment]
service ssh restart 是 centos 6 的命令。centos 7 的命令是： sshd.

**Comment by TomShawn** [comment]
/remove-translation doing
/unassign @Joyinqin 
@asddongmen To better manage PRs in this repo, I'll close this PR for now. If you have further update, feel free to reopen it. Thanks!

**Pull request closed without merging**
