### PR TITLE
Update troubleshoot-ticdc.md

### PR DESCRIPTION
**Pull request by Wu-Yongjian**
cdc cli changefeed update did not have the flag for --start-ts, currently if want to skip DDL  should recreate the changefeed and define the --start-ts with last tso+1

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.
yes
### What is changed, added or deleted? (Required)
modify

### Which TiDB version(s) do your changes apply to? (Required)
6.1.0

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v6.2 (TiDB 6.2 versions)
- [x ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [x ] Need modification after applied to another branch 
- [x ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by shichun-0415** [comment]
@Wu-Yongjian Is your PR applicable only to v6.1, or applicable to v6.1 and later versions (such as the upcoming v6.2)？

**Comment by Wu-Yongjian** [comment]
@shichun-0415 I just test this  on the v6.1 have not test on the v6.2, did not know if the "ticdc update" model has implement the 
 "--start-ts" flag, but if it didn't  i think it maybe the same in v6.2

**Comment by shichun-0415** [comment]
> @shichun-0415 I just test this on the v6.1 have not test on the v6.2, did not know if the "ticdc update" model has implement the "--start-ts" flag, but if it didn't i think it maybe the same in v6.2

@leoppro PTAL

**Review by amyangfei — APPROVED** [review]

**Review by shichun-0415 — APPROVED** [review]
LGTM

**Pull request merged**
