### PR TITLE
remove arbiter from v8.1.1

### PR DESCRIPTION
**Pull request by Oreoxmt**
### What is changed, added or deleted? (Required)

Removes `arbiter` from `TiDB-community-toolkit` in v8.1.1 and later v8.1.x patch releases.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [ ] master (the latest development version)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [x] v8.1 (TiDB 8.1 versions)
- [ ] v8.0 (TiDB 8.0 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/tidb-binlog/pull/1309, https://github.com/PingCAP-QE/artifacts/pull/386

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by lilin90** [comment]
@qiancai Please mention this change in https://github.com/pingcap/docs-cn/pull/18278.

**Comment by qiancai** [comment]
> @qiancai Please mention this change in #18278.

Done in [`b93aa4a` (#18278)](https://github.com/pingcap/docs-cn/pull/18278/commits/b93aa4a85f84a6d82164ba0aae4f23ce1b43d4f1)

**Review by lilin90 — APPROVED** [review]
/lgtm

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Pull request merged**
