### PR TITLE
sql: add encrypted-connections.md

### PR DESCRIPTION
**Pull request by breeswish**
@sunhao2017 @shenli PTAL

### CODE REVIEW

**Comment by shenli** [comment]
尽量不要出现 『它』『您』这种词。
Rest LGTM

**Comment by breeswish** [comment]
@shenli Done

**Comment by shenli** [comment]
LGTM

**Comment by tiancaiamao** [comment]
Rename the filename to `encrypted_connections.md`, keep consistent with others.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by breeswish** [comment]
@tiancaiamao Thanks! It is actually `encrypted-connections.md` in the commit. I made a typo in the title and it is fixed now.

**Comment by zhengwanbo** [comment]
LGTM

**Pull request merged**
