### PR TITLE
Fix bad format while exporting to pdf

### PR DESCRIPTION
**Pull request by andelf**
minor changes. WIP

update: WIP, merge this when first pdf document is OK to be published.

### CODE REVIEW

**Comment by c4pt0r** [comment]
Well done!
LGTM

**Comment by andelf** [comment]
TOOD: Rearrange chapters.

**Comment by andelf** [comment]
Ready to be reviewed.

PTAL @c4pt0r @queenypingcap @siddontang @shenli 

BTW: where to put the scripts and latex templates?

**Comment by queenypingcap** [comment]
LGTM. I like it!

**Comment by c4pt0r** [comment]
Create a 'scripts' directory under this repo.

**Comment by c4pt0r** [comment]
LGTM

**Comment by andelf** [comment]
@c4pt0r but a latex template is not a script. :rofl:

**Comment by c4pt0r** [comment]
Your script depends on this template, so basically it's a part of script. XD

**Pull request merged**
