### PR TITLE
op-guide/tune-tikv.md: fix a rocksdb-docs link

### PR DESCRIPTION
**Pull request by innerr**

### CODE REVIEW

**Comment by c4pt0r** [comment]
Pls sigh the CLA~

**Comment by innerr** [comment]
Sighed.
Keep the links work may be the best before anything changed.

**Comment by innerr** [comment]
And, may be somebody ref the new url as we ref the old one, that would be a mess.

**Comment by c4pt0r** [comment]
Make sense. LGTM

**Comment by shenli** [comment]
LGTM

**Comment by shenli** [comment]
@innerr Thanks！

**Pull request merged**
