### PR TITLE
reference: update command and default value in pd-control

### PR DESCRIPTION
**Pull request by lhy1024**
### What is changed, added or deleted? 
current help:
```
# ./pd-ctl --help
Usage of ./pd-ctl:
      --cacert string   path of file that contains list of trusted SSL CAs.
      --cert string     path of file that contains X509 certificate in PEM format.
  -d, --detach          Run pdctl without readline (default true)
  -i, --interact        Run pdctl with readline
      --key string      path of file that contains X509 key in PEM format.
  -u, --pd string       The pd address (default "http://127.0.0.1:2379")
  -V, --version         print version information and exit
pflag: help requested
```
https://github.com/pingcap/pd/blob/release-3.0/tools/pd-ctl/main.go#L44
update doc to follow usage.

### CODE REVIEW

**Comment by lilin90** [comment]
@dcalvin FYI. Please update the corresponding file in tikv.org after this PR is merged.

**Comment by lhy1024** [comment]
> Does your change apply to `dev` (the latest development version) or `v2.1`? If yes, please also update. Thanks! 

@lilin90 It need to change in `dev`, but it need not  in `v2.1`, because of https://github.com/pingcap/pd/blob/6e44953bec17cb882502007042de77edfb1503e8/tools/pd-ctl/main.go#L43

**Comment by lilin90** [comment]
@lhy1024 Got it! Then please update `dev`.

**Comment by lhy1024** [comment]
> @lhy1024 Got it! Then please also update `dev` in this PR.

@lilin90 done

**Comment by lilin90** [comment]
@nolouch PTAL

**Comment by rleungx** [comment]
It's better to explain what `-i` means

**Comment by lhy1024** [comment]
> It's better to explain what `-i` means

I think the title is enough.

**Pull request merged**
