### PR TITLE
Fix an inconsistency between description and config

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed, added or deleted? (Required)

The configuration is not consistent with the description text.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### CODE REVIEW

**Comment by sticnarf** [comment]
PTAL @yikeke

**Review by yikeke — APPROVED** [review]
LGTM

**Pull request merged**
