### PR TITLE
Update grafana-tidb-dashboard.md

### PR DESCRIPTION
**Pull request by xyqcmss**
这一行在新的v5.0.0-rc的监控页面中没有，
    - Wait Duration 95：等待处理的 Batch 消息延迟

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [x] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by xyqcmss** [comment]
/cc @TomShawn
辛苦您，看一下！

**Comment by TomShawn** [comment]
@xyqcmss "这一行在新的v5.0.0-rc的监控页面中没有" This means that the PR content is only applicable to release-5.0 and master, not to release-4.0. But this PR is based on release-4.0 and will be merged to this branch first. I am afraid that you will need to create another PR to delete this line BASED ON the MASTER branch.
image

**Comment by xyqcmss** [comment]
/cc @TomShawn
Okay, thank you for your guidance, I will change this version and resubmit

**Comment by TomShawn** [comment]
The new PR is https://github.com/pingcap/docs-cn/pull/5753.
@xyqcmss Could you please close this PR? Thanks!

**Comment by xyqcmss** [comment]
/cc @TomShawn
ok，I have closed this PR！
Thanks！

**Pull request closed without merging**
