### PR TITLE
update ticdc recommended disk size

### PR DESCRIPTION
**Pull request by sdojjy**
### First-time contributors' checklist 

- [X] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

update ticdc recommended disk size

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [X] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by TomShawn** [comment]
@sdojjy 是否和版本相关呢？

**Comment by sdojjy** [comment]
> @sdojjy 是否和版本相关呢？

和版本无关，只是根据加大建议的磁盘大小，不然追增量可能有问题。

**Comment by TomShawn** [comment]
> > @sdojjy 是否和版本相关呢？
> 
> 和版本无关，只是根据tikv加大建议的磁盘大小，不然追增量可能有问题。
更改这个值会影响哪些版本呢？

**Review by Liuxiaozhen12 — APPROVED** [review]

**Comment by Liuxiaozhen12** [comment]
> @sdojjy 更改这个值会影响哪些版本呢？改了个值，一定对用户有影响，也正如您说的【不然追增量可能有问题】。用户在哪些 TiDB 版本上用了新值能避免这个问题呢？请选上所有适用的版本。谢谢~

checked with the author. added the necessary cp labels.

**Pull request merged**
