### PR TITLE
Placement rules: fix the version that Placement Rules was introduced

### PR DESCRIPTION
**Pull request by en-jin19**
### What is changed, added or deleted? (Required)
Fixed the version that the Placement Rules was introduced. In 4.0~5.2 branches, the documents say "Placement Rules is...  introduced in v4.0.", but in 5.3 and the master branches, they say "Placement Rules is...  introduced in v5.0.".

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [ ] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs-cn/issues/8236

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by morgo** [comment]
I think this is because:

- Placement rule (PD feature) was introduced in v4.0.
- Placement rules in SQL (i.e. configure it from TiDB) was introduced in 5.0, changed in design and declared experimental in v5.3.

So it might have been correct here. It depends on context.

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
