### PR TITLE
Update production-deployment-using-tiup.md

### PR DESCRIPTION
**Pull request by lonng**
### What is changed, added or deleted? (Required)

The `--refresh` has been removed at TiUP v1.0.0

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### CODE REVIEW

**Comment by yikeke** [comment]
还有一些其他文档也有提及 `--refresh` 参数，要不要批量搜索下都去掉？ @lonng

**Comment by lonng** [comment]
> 还有一些其他文档也有提及 `--refresh` 参数，要不要批量搜索下都去掉？ @lonng

Nice catch, I will address all documents.

**Comment by lonng** [comment]
@yikeke PTAL again.

**Pull request merged**
