### PR TITLE
Update check-before-deployment.md

### PR DESCRIPTION
**Pull request by EspenDai**
https://docs.pingcap.com/zh/tidb/stable/check-before-deployment  ：检测及关闭系统 swap ，显示错误，疑似错误换行符导致。

### What is changed, added or deleted? (Required)

**I'll manually create a PR to cherry-pick this PR to the master branch.**
从官网https://docs.pingcap.com/zh/tidb/stable/check-before-deployment直接看，格式错误，怀疑错误换行符导致
```bash echo "vm.swappiness = 0">> /etc/sysctl.conf swapoff -a && swapon -a sysctl -p ```

复制到文本中，重新添加换行符
```bash
echo "vm.swappiness = 0">> /etc/sysctl.conf
swapoff -a && swapon -a
sysctl -p
```
### Which TiDB version(s) do your changes apply to? (Required)

v.4.0 stable

- [ ] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by ran-huang** [comment]
@EspenDai Hi, thank you for your kind help!
After investigation, we believe the display error you've found is caused by 4 extra spaces under the `{{< copyable "shell-regular" >}}` code snippet. We have fixed this error in this PR (https://github.com/pingcap/docs-cn/pull/4327).

Still, thanks again for spotting the error and reporting it to us.😄

**Pull request merged**
