### PR TITLE
v2.1, v3.0, dev: update links according to the new link format

### PR DESCRIPTION
**Pull request by yikeke**
### What is changed, added or deleted? 

To fix the dead links in GitHub `pingcap/docs-cn` repo, a new link format is adopted. For example, use `/dev/reference/mysql-compatibility.md` instead of `reference/mysql-compatibility.md` when you write a link in the markdown file.

This PR updates all links in v2.1, v3.0 and dev folders.

### What is the related PR or file link(s)? 
Aligned in docs: https://github.com/pingcap/docs/pull/1501

JIRA issue ref: https://internal.pingcap.net/jira/browse/ICM-132

### Which version does your change affect? 

v2.1, v3.0, dev

### CODE REVIEW

**Comment by lilin90** [comment]
FYI. @dcalvin @CaitinChen @TomShawn @juliezhang1112

**Comment by YiniXu9506** [comment]
LGTM

**Comment by cofyc** [comment]
@yikeke 
hi, to support this new link format, you can update `scripts/verify-links.sh` with this change:

```
diff --git a/scripts/verify-links.sh b/scripts/verify-links.sh
index b2b7435..1dd63d1 100755
--- a/scripts/verify-links.sh
+++ b/scripts/verify-links.sh
@@ -47,7 +47,7 @@ for d in dev $(ls -d v[0-9]*); do
     echo "info: checking links under $d directory..."
     sed \
         -e "s#<ROOT>#$ROOT#g" \
-        -e "s#<DOC_ROOT>#$ROOT/$d#g" \
+        -e "s#<DOC_ROOT>#$ROOT#g" \
         scripts/markdown-link-check.tpl > $CONFIG_TMP
     cat $CONFIG_TMP
     # TODO simplify this if markdown-link-check can process multiple files together
```

**Comment by yikeke** [comment]
The CI check script has been updated in this PR according to the new link format. And all link changes in the PR have passed the deadlink check. I think now we are all good and can merge this PR. @YiniXu9506 @cofyc @lilin90

**Comment by YiniXu9506** [comment]
LGTM again! I will let you know once it's ready to merge!

**Comment by yikeke** [comment]
> LGTM again! I will let you know once it's ready to merge!

Okay.

**Pull request merged**
