### PR TITLE
tiny refine cert based authentication

### PR DESCRIPTION
**Pull request by lysu**
### What is changed, added or deleted? (Required)

tiny refine cert based authentication

- cleanup 3.0.x info when it's in 4.0 docs
- remove install openssl and replace it to enable client-mysql tls docs linke

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

---
This change is [Reviewable](https://reviewable.io/reviews/pingcap/docs-cn/3328)

### CODE REVIEW

**Comment by lysu** [comment]
need merge https://github.com/pingcap/docs-cn/pull/3325 firstly, then this pr can pass dead link check

**Comment by TomShawn** [comment]
This PR must be merged after https://github.com/pingcap/docs-cn/pull/3325.

**Comment by TomShawn** [comment]
LGTM

**Pull request merged**
