### PR TITLE
Update tidb-lightning-configuration.md

### PR DESCRIPTION
**Pull request by pepezzzz**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

merge route section from 
https://docs.pingcap.com/zh/tidb/v5.4/tidb-lightning-backends#%E4%BB%8E-loader-%E8%BF%81%E7%A7%BB%E5%88%B0-tidb-lightning-tidb-backend

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.2 (TiDB 6.2 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by sunzhaoyang** [comment]
Reject

我之前有提 PR 加进去，后来又删掉。理由是 route 这个特性尚未 GA，而且和 mydumper.files 特性有冲突。两个特性一起用的后果不确定，也没人讲的清。

**Comment by pepezzzz** [comment]
> 

https://docs.pingcap.com/zh/tidb/v5.0/tidb-lightning-backends#%E4%BB%8E-loader-%E8%BF%81%E7%A7%BB%E5%88%B0-tidb-lightning-tidb-backend

根据这个文档， lightning 的 route 功能是用来替代 loader 的，如果这个功能没 GA （其实现场一直在用），是不是要推动 GA？

**Comment by ran-huang** [comment]
img_v2_fc763c41-ed5e-4c68-9168-ecc8e8e55dbg

from @Frank945946 : 
> 用这个参数代替了，所以不需要加到文档里了
> https://docs.pingcap.com/zh/tidb/v7.0/tidb-lightning-configuration

没有其他问题的话，这个 PR 就关了哈

**Comment by pepezzzz** [comment]
这个 PR 可以关闭，现在我们都是用 shell 改名的方式来实现 route。
pattern 这个特性应该是只能支持 parquet 文件。

**Pull request closed without merging**
