### PR TITLE
ticdc: update max-batch-size

### PR DESCRIPTION
**Pull request by overvenus**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Comment by TomShawn** [comment]
@overvenus 这个默认值变更，是之前一直写错了，还是从哪个版本起发生了变化呢？

**Review by asddongmen — APPROVED** [review]

**Review by hfxsd — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
> @overvenus 这个默认值变更，是之前一直写错了，还是从哪个版本起发生了变化呢？

v4.0.13 调整的

**Comment by TomShawn** [comment]
> > @overvenus 这个默认值变更，是之前一直写错了，还是从哪个版本起发生了变化呢？
> 
> v4.0.13 调整的

可否理解为 v4.0.13 以后版本的默认值都是 16 呢？v5.0.1 是早于 v4.0.13 的，v5.0 分支是从哪个 patch 版本改的呢？
image

**Comment by overvenus** [comment]
> > > @overvenus 这个默认值变更，是之前一直写错了，还是从哪个版本起发生了变化呢？
> > 
> > 
> > v4.0.13 调整的
> 
> 可否理解为 v4.0.13 以后版本的默认值都是 16 呢？v5.0.1 是早于 v4.0.13 的，v5.0 分支是从哪个 patch 版本调整的呢？v5.0.2 吗？ image
> 
> 且 [TiDB 4.0.13 Release Notes | PingCAP Docs](https://docs.pingcap.com/zh/tidb/stable/release-4.0.13) 中并没有加上这一条

该改动来自 https://github.com/pingcap/ticdc/pull/1650

带入版本如下：

* 大于等于 4.0.13 的 4.0.x 版本
* 大于等于 5.0.1 的 5.0.x 版本
* 所有大于等于 5.1.x 的版本

**Review by Liuxiaozhen12 — APPROVED** [review]

**Pull request merged**
