### PR TITLE
Remove the swappiness parameter

### PR DESCRIPTION
**Pull request by glkappe**
repeat

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by glkappe** [comment]
There is another problem. The modification of sysctl conf is in the form of `echo`. There is a high probability that the parameters will be repeated. The previous parameter takes effect. How to modify the way the parameters take effect? ​​When a large cluster is deployed, it is not very convenient

**Comment by King-Dylan** [comment]
目的是为了修改参数，如果 echo 有问题那可以改成 vim 进去手工修改添加的方式。这个 pr 这里只是删了 swappiness 参数。

**Comment by TomShawn** [comment]
> 目的是为了修改参数，如果 echo 有问题那可以改成 vim 进去手工修改添加的方式。这个 pr 这里只是删了 swappiness 参数。

@glkappe Any update?

**Comment by glkappe** [comment]
> 目的是为了修改参数，如果 echo 有问题那可以改成 vim 进去手工修改添加的方式。这个 pr 这里只是删了 swappiness 参数。

优化 quick start，让它能复制粘贴不需要修改就可以执行，如果只是为了让用户「你应该修改这个」，那这个价值就很低。

目的还是如何优化这个 <copy>，真实使用遇到的很麻烦的问题。

**Comment by King-Dylan** [comment]
我明白你意思，但是你这个 pr 只是删了一行而已

**Comment by dveeden** [comment]
If this gets removed from the docs then `tiup cluster check ...` should also be modified.
https://github.com/pingcap/tiup/blob/45e4471d4c627ff367253a69ef3f9c13bf79ddbe/pkg/cluster/operation/check.go#L407-L416

**Comment by King-Dylan** [comment]
from glkappe  删了这一行是因为前面步骤已经执行，重复了

**Review by King-Dylan — APPROVED** [review]

**Comment by TomShawn** [comment]
> If this gets removed from the docs then `tiup cluster check ...` should also be modified.
> https://github.com/pingcap/tiup/blob/45e4471d4c627ff367253a69ef3f9c13bf79ddbe/pkg/cluster/operation/check.go#L407-L416

@lucklove @AstroProfundis FYI

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
