### PR TITLE
Fix typo 

### PR DESCRIPTION
**Pull request by eBoyy**
Fix typo for "元信息".

### CODE REVIEW

**Comment by shenli** [comment]
@eBoyy Thanks!   LGTM
Please sign the CLA.

**Comment by eBoyy** [comment]
@shenli Have signed the CLA and added my email address used for this commit to my account, but still can't pass the CLA test.
I'll try it later.

**Comment by shenli** [comment]
@siddontang PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by c4pt0r** [comment]
LGTM

**Comment by eBoyy** [comment]
Clear the cookies and re-sign the CLA, pass the CLA test finally.
Not sure if it's a bug.

**Pull request merged**
