### PR TITLE
tools: add  a tip for binlogctl's usage

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What is changed, added or deleted? 

add a tip for binlogctl

### Which version does your change affect? 

dev, v3.0 and v2.1

### Checklist 

- [] Add a new file to `TOC.md`
- [ x] No Tab spaces anywhere 
- [ x] Leave a blank line both before and after a code block
- [x ] Keep the first level heading consistent with `title` in metadata
- [ x] Use *four* spaces for each level of indentation except that in `TOC.md`

### CODE REVIEW

**Comment by ericsyh** [comment]
LGTM 
@WangXiangUSTC Need to update the file under /v3.0/ and /v2.1/ also.

**Comment by lilin90** [comment]
@WangXiangUSTC Please address @ericsyh's comment.

**Comment by WangXiangUSTC** [comment]
after this pr is merged, I will update v2.1 and v3

**Comment by lilin90** [comment]
> after this pr is merged, I will update v2.1 and v3 @ericsyh @lilin90

That's good.

**Pull request merged**
