### PR TITLE
remove system variable `tidb_track_aggregate_memory_usage`

### PR DESCRIPTION
**Pull request by wshwsh12**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

remove system variable `tidb_track_aggregate_memory_usage`

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): https://github.com/pingcap/tidb/pull/23184

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
/Needs-cherry-pick-5.0,v5.0

**Comment by qiancai** [comment]
/Needs-cherry-pick-5.0, v5.0

**Comment by qiancai** [comment]
/needs-cherry-pick-5.0, v5.0

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by qiancai** [comment]
LGTM

**Comment by qiancai** [comment]
@Joyinqin, the content in this PR is ready for translation. PTAL, thanks!

**Pull request merged**
