### PR TITLE
Media: Update syncer-sharding.png

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
 Update syncer-sharding.png

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/4208
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by yikeke** [comment]
Please help align [this config change](https://github.com/pingcap/docs-cn/pull/4874/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R24) in other repos. @CharLotteiu

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
> Please help align [this config change](https://github.com/pingcap/docs-cn/pull/4874/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R24) in other repos. @CharLotteiu

Already aligned https://github.com/pingcap/docs/blame/master/.circleci/config.yml#L31

**Pull request merged**
