### PR TITLE
update stale read doc for ga

### PR DESCRIPTION
**Pull request by NingLin-P**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions) 补充是从 v5.1.1 GA 的
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
是否需要说明一下，Stale Read 是从哪个 TiDB版本起 GA 的？

**Comment by NingLin-P** [comment]
> 是否需要说明一下，Stale Read 是从哪个 TiDB版本起 GA 的？

从 v5.1.1 开始，这个具体要写到那个文档呀，还是只要写到 release note 就可以了

**Comment by nolouch** [comment]
lgtm, cc @Yisaer

**Comment by TomShawn** [comment]
> > 是否需要说明一下，Stale Read 是从哪个 TiDB版本起 GA 的？
> 
> 从 v5.1.1 开始，这个具体要写到那个文档呀，还是只要写到 release note 就可以了

写到 cherry-pick 到 release-5.1 的文档中

**Review by Yisaer — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
