### PR TITLE
Update enable joint consensus default value

### PR DESCRIPTION
**Pull request by qiancai**
### What is changed, added or deleted? (Required)

Update the default value of enable-joint-consensus from false to true for 5.0GA according to the confirmation from Jay

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/5188 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by BusyJay** [comment]
Just to clarify, it's still false in 5.0-rc and becomes true in 5.0.

**Review by BusyJay — APPROVED** [review]

**Comment by qiancai** [comment]
@Joyinqin, the review is done. Please create the corresponding English PR. Thanks!

**Comment by TomShawn** [comment]
@qiancai Please sign the CLA for this PR to be merged, thanks!

**Comment by qiancai** [comment]
Close the PR due to the CLA issue

**Pull request closed without merging**
