### PR TITLE
system-variable: add a warning message for `tidb_partition_prune_mode` variable

### PR DESCRIPTION
**Pull request by Defined2014**
### What is changed, added or deleted? (Required)

Deprecated static prune mode, ref https://github.com/pingcap/tidb/issues/56490

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v8.5 (TiDB 8.5 versions)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): ref https://github.com/pingcap/tidb/pull/56543

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by mjonss — COMMENTED** [review]
I think also https://docs.pingcap.com/tidb/stable/partitioned-table, https://docs.pingcap.com/tidb/stable/use-tiflash-mpp-mode and https://docs.pingcap.com/tidb/stable/tiflash-upgrade-guide also needs updating?

**Comment by Defined2014** [comment]
> I think also https://docs.pingcap.com/tidb/stable/partitioned-table, https://docs.pingcap.com/tidb/stable/use-tiflash-mpp-mode and https://docs.pingcap.com/tidb/stable/tiflash-upgrade-guide also needs updating?

I will do it when we remove `staitc` prune mode. In v8.5, I only mentioned it will deprecated in the future.

**Comment by mjonss** [comment]
> > > > I think also https://docs.pingcap.com/tidb/stable/partitioned-table, https://docs.pingcap.com/tidb/stable/use-tiflash-mpp-mode and https://docs.pingcap.com/tidb/stable/tiflash-upgrade-guide also needs updating?
> > > 
> > > 
> > > I'll do this when we remove `static prune mode`, maybe v9.2. In v8.5 I only mentioned that it will be deprecated in the future.
> > 
> > 
> > There is a minor issue, that the examples will not output the same:
> > ```sql
> > mysql> SET tidb_partition_prune_mode=static;
> > Query OK, 0 rows affected (0.00 sec)
> > ```
> > vs
> > ```sql
> > tidb> set @@tidb_partition_prune_mode='static';
> > Query OK, 0 rows affected, 1 warning (0.00 sec)
> > ```
> > 
> >   
> > I.e. it will start showing a warning.
> 
> I can't reproduce it.
> 

So now it will have the additional `, 1 warning` in the output, since it is deprecated :)
And before this version/PR it will not have a warning, so that is the difference.

**Comment by Defined2014** [comment]
> > > > > I think also https://docs.pingcap.com/tidb/stable/partitioned-table, https://docs.pingcap.com/tidb/stable/use-tiflash-mpp-mode and https://docs.pingcap.com/tidb/stable/tiflash-upgrade-guide also needs updating?
> > > > 
> > > > 
> > > > I'll do this when we remove `static prune mode`, maybe v9.2. In v8.5 I only mentioned that it will be deprecated in the future.
> > > 
> > > 
> > > There is a minor issue, that the examples will not output the same:
> > > ```sql
> > > mysql> SET tidb_partition_prune_mode=static;
> > > Query OK, 0 rows affected (0.00 sec)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > vs
> > > ```sql
> > > tidb> set @@tidb_partition_prune_mode='static';
> > > Query OK, 0 rows affected, 1 warning (0.00 sec)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I.e. it will start showing a warning.
> > 
> > 
> > I can't reproduce it.
> 
> So now it will have the additional `, 1 warning` in the output, since it is deprecated :) And before this version/PR it will not have a warning, so that is the difference.

Yes. It will take two more LTS releases to let users know it's deprecated.

**Review by mjonss — APPROVED** [review]

**Review by lilin90 — APPROVED** [review]
/lgtm

**Review by hfxsd — APPROVED** [review]

**Pull request merged**
