### PR TITLE
reference: change "region miss-peer" to "region check miss-peer"

### PR DESCRIPTION
**Pull request by TaoZhengCN**
修改 region miss-peer 为 region check miss-peer

### CODE REVIEW

**Comment by lilin90** [comment]
@dcalvin FYI. Update about PD Control.

**Comment by lilin90** [comment]
> Does your change also apply to `dev` or `v2.1`? If yes, please also update.

@TaoZhengCN Please address the comment. Thanks!

**Comment by TaoZhengCN** [comment]
> > Does your change also apply to `dev` or `v2.1`? If yes, please also update.
> 
> @TaoZhengCN Please address the comment. Thanks!

yes

**Comment by lilin90** [comment]
@TaoZhengCN Then please also update `dev` and `v2.1`.

**Comment by TomShawn** [comment]
@TaoZhengCN When the content is ready, please also update v3.1 as well, thanks~

**Comment by lilin90** [comment]
@TaoZhengCN The same change has been done in #1845, so I'll close this PR.

**Pull request closed without merging**
