### PR TITLE
update SPM documentation for DML SQL Bind and baseline capture (#5740)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #5740 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs-cn repo:
git pr https://github.com/pingcap/docs-cn/pull/5785
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs-cn.git pr/5785:release-4.0-00b75c2c6ec4
```

---

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/tidb/pulls?q=is%3Apr+is%3Aclosed+label%3Aepic%2Fsql-plan-management

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by yikeke** [comment]
Is this a PR related to the next release v4.0.12? @eurekaka

**Comment by TomShawn** [comment]
@eurekaka @yikeke Can we merge this PR now?

**Comment by eurekaka** [comment]
Yes, it is related to v4.0, I think it is ready for merge.

**Pull request merged**
