### PR TITLE
Update grafana-tikv-dashboard.md

### PR DESCRIPTION
**Pull request by newHE3DBer**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Update grafana-tikv-dashboard.md，delete Split check CPU and update BackGround worker CPU

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [x] Delete files
- [x] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by newHE3DBer** [comment]
\cc @TomShawn

**Comment by TomShawn** [comment]
@newHE3DBer Could you please sign [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn?pullRequest=5744) for this PR to be merged? Thanks!

**Comment by newHE3DBer** [comment]
删除delete Split check CPU and 更新 BackGround worker CPU

**Comment by jackysp** [comment]
> 
> 
> /cc @jackysp

not sure about it

**Comment by newHE3DBer** [comment]
这一行在新的v5.0.0-rc的监控页面tikv-details监控界面中## Thread CPU中没有delete Split check CPU指标
和Snapshot worker CPU应该更新为BackGround worker CPU

**Comment by newHE3DBer** [comment]
image
这一行在新的v5.0.0-rc的监控页面tikv-details监控界面中## Thread CPU中没有delete Split check CPU指标
和Snapshot worker CPU应该更新为BackGround worker CPU

**Comment by newHE3DBer** [comment]
image
这是4.0的指标，master没有更新监控页面tikv-details监控界面中## Thread CPU中没有delete Split check CPU指标
和Snapshot worker CPU应该更新为BackGround worker CPU

**Comment by jackysp** [comment]
> 
> 
> /cc @jackysp

Sorry I mean I'm not familiar with tikv dashboard. PTAL @MyonKeminta

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
