### PR TITLE
sql-statements: fix punctuation and format

### PR DESCRIPTION
**Pull request by Pearla-techwriter**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@Pearla-techwriter Thanks for making a contribution. Would you please sign the CLA as indicated by CLAassistant?

**Comment by Pearla-techwriter** [comment]
Can you tell me more about CLAassistant?



发自我的iPhone


------------------ Original ------------------

**Comment by TomShawn** [comment]
@Pearla-techwriter Please see the following two images for instruction. I believe that it once appeared on your screen.:)

image
image

**Comment by Pearla-techwriter** [comment]
Sorry, two images you sent me fail to display on my computer.&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by TomShawn** [comment]
@Pearla-techwriter You can click on [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn) and sign the CLA. Otherwise, your pull request cannot be merged.

**Comment by TomShawn** [comment]
@Pearla-techwriter Any update?

**Comment by TomShawn** [comment]
@Pearla-techwriter To better manage PRs in this repo, I'll close this one for now. If you have any updates, feel free to reopen it.

**Pull request closed without merging**
