### PR TITLE
Update related description in troubleshoot-tiflash

### PR DESCRIPTION
**Pull request by glkappe**
与 https://pingcap.com/docs-cn/stable/configure-placement-rules/ 中描述冲突：

开启 Placement Rules 后，原先的 max-replicas 及 location-labels 配置项将不再生效。如果需要调整副本策略，应当使用 Placement Rules 相关接口。

### What is changed, added or deleted? (Required)

Manually cherry-picked to `master` in https://github.com/pingcap/docs-cn/pull/3418.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
@glkappe Please rebase this PR to the master branch if it applies to both master and release-4.0. Please also involve a technical review.

**Comment by rleungx** [comment]
> “检查 PD 配置的 max-replicas 是否小于等于集群 TiKV 节点数。若 max-replicas 超过 TiKV 节点数，则 PD 不会向 TiFlash 同步数据“

Do we also need to change it?

**Comment by glkappe** [comment]
> > “检查 PD 配置的 max-replicas 是否小于等于集群 TiKV 节点数。若 max-replicas 超过 TiKV 节点数，则 PD 不会向 TiFlash 同步数据“
> 
> Do we also need to change it?

https://docs.pingcap.com/zh/tidb/stable/configure-placement-rules#%E5%BC%80%E5%90%AF-placement-rules-%E7%89%B9%E6%80%A7
不知道该文档要合并到哪里，官方问答重构之后这方面已经修改了。

**Comment by rleungx** [comment]
@glkappe 我的意思是修改的内容和这个小标题对不上，`max-replicas` 其实是个参数

**Pull request merged**
