### PR TITLE
Refactor tiup

### PR DESCRIPTION
**Pull request by lucklove**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
2021-03-11: According to the PR author @lucklove, the doc changes of this PR will not be part of 5.0 GA, and there is no clear plan for these changes.

**Comment by TomShawn** [comment]
TiUP docs for 5.0 GA is in https://github.com/pingcap/docs-cn/pull/5728.

**Comment by TomShawn** [comment]
/remove-v5.0

**Comment by TomShawn** [comment]
/remove-v5.0

**Comment by TomShawn** [comment]
/remove-v5.0

**Comment by yikeke** [comment]
> TiUP docs for 5.0 GA is in #5728.

@TomShawn So this PR can be closed?

**Comment by TomShawn** [comment]
> > TiUP docs for 5.0 GA is in #5728.
> 
> @TomShawn So this PR can be closed?

This PR includes v5.0 GA-related content AND OTHER CONTENT. @lucklove now separates the v5.0 GA-related content to #5728 and we will focus on #5728 before 5.0 GA release. In this PR, several other documents are added, now still in draft. I think closing this one is OK. @lucklove What do you think?

**Comment by lucklove** [comment]
> > > TiUP docs for 5.0 GA is in #5728.
> > 
> > 
> > @TomShawn So this PR can be closed?
> 
> This PR includes v5.0 GA-related content AND OTHER CONTENT. @lucklove now separates the v5.0 GA-related content to #5728 and we will focus on #5728 before 5.0 GA release. In this PR, several other documents are added, now still in draft. I think closing this one is OK. @lucklove What do you think?

It's OK to close this PR

**Pull request closed without merging**
