### PR TITLE
reference: change default value for two tidb-specific variables

### PR DESCRIPTION
**Pull request by ran-huang**
…b_ddl_reorg_batch_size

### What is changed, added or deleted? (Required)

change `tidb_ddl_reorg_worker_cnt` default value from 16 to 4
change `tidb_ddl_reorg_batch_size` default value from 1024 to 256

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version, including v4.0 changes for now)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

**If you select two or more versions from above**, to trigger the bot to cherry-pick this PR to your desired release version branch(es), you **must** add corresponding labels such as **needs-cherry-pick-3.1**, **needs-cherry-pick-3.0**, and **needs-cherry-pick-2.1**.

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/1971
- Other reference link(s):

### CODE REVIEW

**Comment by ran-huang** [comment]
@tsthght  PTAL😀

**Comment by tsthght** [comment]
LGTM

**Comment by yikeke** [comment]
要不可以cp了以后再做相应的改动，减少你挨个提pr的工作量？

**Comment by ran-huang** [comment]
@yikeke 好的，done！

**Pull request merged**
