### PR TITLE
media: refine one image

### PR DESCRIPTION
**Pull request by TomShawn**
### What is changed, added or deleted? (Required)

Refine `tikv-arch.png`.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by lilin90 — COMMENTED** [review]
How about keeping the original "RocksDB" in this image?

**Review by lilin90 — APPROVED** [review]
LGTM

**Comment by lilin90** [comment]
@TomShawn It seems that the image on the [TiKV 简介 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/dev/tikv-overview) page is still the old one and the change in this PR didn't take effect. Please check and follow up. Thanks!

**Comment by TomShawn** [comment]
> @TomShawn It seems that the image on the [TiKV 简介 | PingCAP Docs](https://docs.pingcap.com/zh/tidb/dev/tikv-overview) page is still the old one and the change in this PR didn't take effect. Please check and follow up. Thanks!

Thanks for feedback! The new one takes effect now.
image

**Pull request merged**
