### PR TITLE
CI/PDF: add watermark, add auto upload to ci

### PR DESCRIPTION
**Pull request by andelf**
- add PingCAP logo watermark to PDF
- add copyright message at the end of PDF
- now all pics under `media` dir
- rename some pics' filenames, avoid misleading
- CI: auto upload PDF to download.pingcap.org

### CODE REVIEW

**Comment by andelf** [comment]
PDF doc for review:
https://transfer.sh/ZoxjC/tidb-doc-cn.pdf

**Comment by andelf** [comment]
@siddontang @c4pt0r @ngaut PTAL

**Comment by iamxy** [comment]
Good job! LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
