### PR TITLE
Update parameter type description

### PR DESCRIPTION
**Pull request by glkappe**
https://github.com/pingcap/tidb/blob/2bf2a82a3df300df4618451de1f16f6c1c1d67bb/config/config.toml.example#L254
0 change to 0s, Explain that the parameter type is string

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@glkappe Would you involve a technical review?

**Comment by glkappe** [comment]
@TomShawn Thank you very much, technical review is needed

**Review by TomShawn — APPROVED** [review]
According to @XuHuaiyu, it is correct.

**Comment by TomShawn** [comment]
@qiancai Please help align this PR, thanks!

**Pull request merged**
