### PR TITLE
Improve the bg_task_io_rate_limit parameter description

### PR DESCRIPTION
**Pull request by glkappe**
This is not a complete parameter description. It needs to be added: supported units（MB？KB？GB？None）, basic risk reminders, how to adjust to reach the ideal value (512M? Decrease/increase to the x power of 2 each time? +)

I don’t understand these, you can directly change the file, and I will agree to commited

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by glkappe** [comment]
My edit may be wrong, please conduct a technical review, THX

**Comment by lidezhu** [comment]
More explanation added in this pr: https://github.com/pingcap/docs-cn/pull/5739.

**Comment by TomShawn** [comment]
> More explanation added in this pr: #5739.

Since you have created another PR with more detailed description, shall we close this PR?

**Comment by lidezhu** [comment]
> > More explanation added in this pr: #5739.
> 
> Since you have created another PR with more detailed description, shall we close this PR?

I think it's ok to close this PR.

**Comment by TomShawn** [comment]
@glkappe What about closing this one?

**Pull request closed without merging**
