### PR TITLE
Update SQL Keywords and Reserved Words to CAPS

### PR DESCRIPTION
**Pull request by imp2002**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Update SQL Keywords and Reserved Words to CAPS

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):
https://github.com/pingcap/docs-cn/issues/2825
https://github.com/pingcap/docs-cn/blob/master/mysql-compatibility.md

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [x] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by imp2002** [comment]
@TomShawn 您好, 5.0, 4.0是学bot再开两个pr分别合到对应分支对吗(´･ω･`)?

**Comment by TomShawn** [comment]
> @TomShawn 您好, 5.0, 4.0是学bot再开两个pr分别合到对应分支对吗(´･ω･`)?

谢谢您参与 TiDB 文档！不需要的单独给 5.0 和 4.0 提 PR。这个 PR 合并后，bot 会自动在 5.0 和 4.0 分支生成 PR 的。

**Pull request merged**
