### PR TITLE
Correct the max column count in tidb-limitations.md

### PR DESCRIPTION
**Pull request by kissmydb**
columns limit is 512 for v4.0

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by kissmydb** [comment]
和 文俊确认过，只在 5.0 改了

**Comment by morgo** [comment]
See: https://github.com/pingcap/docs/issues/4553

The max is 4096, the default is 1017.

**Comment by TomShawn** [comment]
> See: [pingcap/docs#4553](https://github.com/pingcap/docs/issues/4553)
> 
> ~The max is 4096, the default is 1017.~
> 
> **Edit:** Ahh I see. The cherry-pick was closed and not merged. Okay, looks like it is incorrect.

The cherry-picked PR was merged.
image

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
