### PR TITLE
grafana-overview-dashboard: update the monitoring item for CPS

### PR DESCRIPTION
**Pull request by qiancai**
### What is changed, added or deleted? (Required)

Fixed the issue reported in https://asktug.com/t/topic/95634

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
@TomShawn I'll deal with the cherry-pick PRs after this PR is merged.

**Review by TomShawn — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Comment by qiancai** [comment]
@TomShawn The translation of this PR is done. Sorry for missing adding the translation/done label.

**Pull request merged**
