### PR TITLE
how-to/deploy: update Drainer configuration to fix an error

### PR DESCRIPTION
**Pull request by yilongrong**
ERROR MESSAGE SUMMARY *******************************************************************************************************************************************************************************************
[drainer_mysql]: Ansible FAILED! => playbook: deploy_drainer.yml; TASK: drainer_cluster : Preflight check - ensure that the customized config file `/home/tidb/ryl/tidb-ansible/conf/drainer_mysql_drainer-cluster.toml` exists; message: {"changed": false, "msg": "You need to create customized config file `/home/tidb/ryl/tidb-ansible/conf/drainer_mysql_drainer-cluster.toml`."}

### CODE REVIEW

**Comment by lilin90** [comment]
@yilongrong Please don't use Chinese characters in docs-cn PR titles or commit messages. See [Commit Message and Pull Request Style](https://github.com/pingcap/community/blob/master/commit-message-pr-style.md). You can refer to other PRs in this repo as a reference.

**Comment by july2993** [comment]
@lichunzhu PTAL
之前的 pr https://github.com/pingcap/docs-cn/pull/1879  应该改过，确认下

**Comment by lichunzhu** [comment]
@yilongrong 请问能麻烦试一下 v3.0.3 版本的 ansible 吗？应该是从 v3.0.3 以后的 ansible 都不会再需要加 -cluster 了。

**Comment by lilin90** [comment]
@yilongrong PTAL

**Comment by TomShawn** [comment]
@yilongrong When the content is ready, please also update v3.1 as well, thanks~

**Comment by yikeke** [comment]
After this PR merges, sre-bot will automatically cherry-pick this PR to the `release-3.1`, `release-3.0`, and `release-2.1` branches (the `needs-cherry-pick-xxx` labels will trigger the behavior). FYI. @yilongrong @july2993 @lichunzhu

**Comment by liubo0127** [comment]
master 分支不用改，文档是正确的

**Comment by yikeke** [comment]
> master 分支不用改，文档是正确的。
> 最新的 release-3.1、release-3.0 文档与 master 的这部分内容也要保持一致。

哦哦，那就把这个pr关了，重新在release-2.1 branch提这个更改就行～ @yilongrong @liubo0127

**Comment by liubo0127** [comment]
> > master 分支不用改，文档是正确的。
> > 最新的 release-3.1、release-3.0 文档与 master 的这部分内容也要保持一致。
> 
> 哦哦，那就把这个pr关了，重新在release-2.1 branch提这个更改就行～ @yilongrong @liubo0127

嗯嗯，2.1 也不用改，我看了下文档应该正确的，@yilongrong 如果是按文档操作有什么错误，可以提个 issue

**Pull request closed without merging**
