### PR TITLE
Revert "Remove cyclic replication feature: Cherry pick 7336 to release 4.0"

### PR DESCRIPTION
**Pull request by shichun-0415**
Reverts pingcap/docs-cn#7516

Note: According to https://docs.pingcap.com/zh/tidb/v5.3/release-5.3.0#%E7%A7%BB%E9%99%A4%E5%8A%9F%E8%83%BD, cyclic replication is removed from v5.3.0 and should be remained in v4.0.

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]
rest LGTM

**Review by sdojjy — APPROVED** [review]

**Comment by TomShawn** [comment]
https://github.com/pingcap/docs-cn/blob/revert-7516-cherry-pick-7336-to-release-4.0/experimental-features-4.0.md 这篇文档没有加上环形复制。

**Pull request merged**
