### PR TITLE
update patrol-region-interval 10ms -> 50ms

### PR DESCRIPTION
**Pull request by glkappe**
In the case of the default 100ms, the 10ms adjustment is more radical, and in some scenarios may bring a greater burden to the pd-leader.

Please help with technical assessment.

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by rleungx** [comment]
I think this is only an example about how to change the value, not the best practice.

**Comment by glkappe** [comment]
Thanks for your suggestion.

I know, but we can’t limit the user’s behavior, the risk of 50ms is much smaller than 10ms.
PS: The document does not seem to say what the minimum value of this value is, this pr can be added together.

**Review by rleungx — APPROVED** [review]

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
