### PR TITLE
update expression-syntax.md

### PR DESCRIPTION
**Pull request by tangenta**
### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by tangenta** [comment]
@zz-jason updated, 有比较好的建议或参考吗？

**Comment by zz-jason** [comment]
> @zz-jason updated, 有比较好的建议或参考吗？

这个是否可以像其他 SQL Statement 一样画成图呢？

**Comment by tangenta** [comment]
@zz-jason 现在就是 sqlgram 语法图, PTAL

**Pull request merged**
