### PR TITLE
Update quick-start-with-tidb.md

### PR DESCRIPTION
**Pull request by lucklove**
### What is changed, added or deleted? (Required)

Close https://github.com/pingcap/docs-cn/issues/4635

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by lucklove** [comment]
Copy from https://github.com/pingcap/docs-cn/pull/4656

**Review by lonng — APPROVED** [review]
LGTM

**Review by yikeke — APPROVED** [review]

**Pull request merged**
