### PR TITLE
Update a value in tikv-configuration-file.md

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
change the value `0` into `0s`.  https://github.com/tikv/tikv/pull/8283

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/4175
- Other reference link(s): https://github.com/tikv/tikv/pull/8283

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@youjiali1995 Please help confirm the applicable versions. Thanks!

**Review by youjiali1995 — APPROVED** [review]
LGTM

**Comment by youjiali1995** [comment]
v2.1, v3.0, v3.1, v4.0.

**Comment by TomShawn** [comment]
> v2.1, v3.0, v3.1, v4.0.

Thanks! We still decide not to cherry-pick to 2.1 because it's too old to be necessary.

**Pull request merged**
