### PR TITLE
reference/performance: reorder tikv tuning log parameters

### PR DESCRIPTION
**Pull request by glkappe**
### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
@glkappe Thanks for you contribution!
@Little-Wallace PTAL and check all the available versions, thanks~

**Comment by yikeke** [comment]
Please sign the CLA, or this PR cannot be merged because of the CI. @glkappe

**Comment by TomShawn** [comment]
@glkappe Would you mind creating another PR to make this change to the `master`  branch?

**Pull request merged**
