### PR TITLE
dm: add dm task timezone config

### PR DESCRIPTION
**Pull request by glorv**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@glorv 这是 v5.4 生效的配置项吗？

**Comment by lance6716** [comment]
> @glorv 这是 v5.4 生效的配置项吗？

5.3 引入的，文档没更新

https://github.com/pingcap/tiflow/pull/3403

**Review by lance6716 — APPROVED** [review]

**Comment by glorv** [comment]
确实是 5.3 就有的功能，之前遗漏了更新文档了😂

**Review by shichun-0415 — APPROVED** [review]

**Review by hfxsd — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@glorv Only the `dev` version of docs-cn has the DM documentation (`dev`). If you want to modify the DM docs (v5.3 or earlier version), please create a PR in https://github.com/pingcap/docs-dm/tree/release-5.3. Thanks~

**Comment by shichun-0415** [comment]
> @glorv Only the `dev` version of docs-cn has the DM documentation (`dev`). If you want to modify the DM docs (v5.3 or earlier version), please create a PR in https://github.com/pingcap/docs-dm/tree/release-5.3. Thanks~

Have told glorv. He will create the PR in docs-dm 5.3. Thanks Tom for reminding.

**Pull request merged**
