### PR TITLE
fix: text error

### PR DESCRIPTION
**Pull request by Rubik-W**
### What is changed, added or deleted? (Required)

fixed text error

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
@Rubik-W Thanks for your contribution! Please sign the [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn?pullRequest=3976) for this PR to be merged.

**Comment by Rubik-W** [comment]
> @Rubik-W Thanks for your contribution! Please sign the [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn?pullRequest=3976) for this PR to be merged.

done

**Comment by TomShawn** [comment]
@Rubik-W Looks like this PR still shows that you are unsigned. Could you try again by clicking this button in the **Contributor License Agreement** as shown in this https://github.com/pingcap/docs-cn/pull/3976#issuecomment-659117310 comment?
image

**Comment by Rubik-W** [comment]
> @Rubik-W Looks like this PR still shows that you are unsigned. Could you try again by clicking this button in the **Contributor License Agreement** as shown in this [#3976 (comment)](https://github.com/pingcap/docs-cn/pull/3976#issuecomment-659117310) comment?
> image

Thanks, I has retry.

**Comment by lilin90** [comment]
@Rubik-W It seems that you used two accounts, Rubik-W & 温合民？

**Comment by Rubik-W** [comment]
> Rubik-W

Use Rubik-W.

**Comment by TomShawn** [comment]
@Rubik-W Would you create another PR to migrate the change to that PR and only use the **Rubik-W** account? As the CLAassitant says, **温合民** is not a GitHub user and cannot sign the CLA, which means that PRs in this repository with a commit by **温合民** cannot be merged. 
image

**Comment by Rubik-W** [comment]
New PR: #3996

**Pull request closed without merging**
