### PR TITLE
Update compatibility for temporary tables (#5758)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #5758 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In docs-cn repo:
git pr https://github.com/pingcap/docs-cn/pull/5777
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/docs-cn.git pr/5777:release-5.0-fb1b61655b05
```

---

### What is changed, added or deleted? (Required)

Update compatibility for temporary tables for dev and v5.0.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)  --> 需要对版本进行描述：从 v5.0 GA 版本起，
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/5673

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [x] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by bb7133** [comment]
Hi @TomShawn , please update this PR, thanks.

**Comment by TomShawn** [comment]
> Hi @TomShawn , please update this PR, thanks.

Done. PTAL

**Pull request merged**
