### PR TITLE
op-guide: Update ansible-deployment.md `useradd` command

### PR DESCRIPTION
**Pull request by Lunatictwo**
By default, `useradd` will not create home dir for new user automatically, and `useradd` is a low level utility for adding users. Set -m and -d will create tidb dir.

### CODE REVIEW

**Comment by Lunatictwo** [comment]
@CaitinChen

**Comment by lilin90** [comment]
@Lunatictwo Thanks for your contribution! @LinuxGit PTAL

**Comment by LinuxGit** [comment]
```
$ grep -B4 CREATE_HOME /etc/login.defs
# If useradd should create home directories for users by default
# On RH systems, we do. This option is overridden with the -m flag on
# useradd command line.
#
CREATE_HOME	yes
```
@Lunatictwo On CentOS7, useradd will create home directory by default. What's your Linux destro and version?
Adding -m -d /home/tidb flags is better.
LGTM, Thanks.

**Comment by Lunatictwo** [comment]
@LinuxGit Ubuntu 16.04.4 LTS at AWS

**Comment by LinuxGit** [comment]
Thanks for your feedback.

**Comment by sjvs** [comment]
> LGTM, Thanks.

See [LGTM.com](http://lgtm.com/projects/g/pingcap/docs-cn) for pingcap/docs-cn code analysis: http://lgtm.com/projects/g/pingcap/docs-cn. Enable automatic code review here: http://lgtm.com/projects/g/pingcap/docs-cn/ci

**Pull request merged**
