### PR TITLE
reference: add a description in the mysql-compatibility doc

### PR DESCRIPTION
**Pull request by glkappe**
- 不支持通过 `ALTER TABLE` 在所生成的列上添加索引

添加必要说明，或者附上 `generated column` 链接，避免用户曲解为 add column a int，紧接着 add index idx_a(a); 不支持
https://asktug.com/t/topic/34175

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by Deardrops** [comment]
`release-3.0` also need this change, and `release-4.0` should remove this limit.

I will file a PR for `release-4.0`, could you file a same PR for `release-3.1`?

**Comment by TomShawn** [comment]
> `release-3.1` also need this change, and `release-4.0` should remove this limit.
> 
> I will file a PR for `release-4.0`, could you file a same PR for `release-3.1`?

I think we can use cherry-pick tags to make these changes to `release-3.1` and `release-4.0`. Would you mind creating another PR to make these changes to thee `master` branch?

**Comment by TomShawn** [comment]
> `release-3.1` also need this change, and `release-4.0` should remove this limit.
> 
> I will file a PR for `release-4.0`, could you file a same PR for `release-3.1`?

You have removed this line `不支持通过 `ALTER TABLE` 在所生成的列上添加索引` in 4.0 and dev. Do you mean that 3.1 needs the change of this PR, instead of removing this line?

**Comment by Deardrops** [comment]
> You have removed this line `不支持通过 `ALTER TABLE` 在所生成的列上添加索引` in 4.0 and dev. Do you mean that 3.1 needs the change of this PR, instead of removing this line?

Yes, 3.1 and 3.0 change the line, while 4.0 and dev remove this line.

**Pull request merged**
