### PR TITLE
Remove @@ modification method

### PR DESCRIPTION
**Pull request by glkappe**
去掉
SET @@global.tidb_distsql_scan_concurrency = 10;
修改 global 环境变量的方式，这边在 v3.0.12,v4.0.1测试并不生效，辛苦评估下

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by glkappe** [comment]
add：
https://asktug.com/t/topic/36702/11?u=%E6%88%B7%E5%8F%A3%E8%88%9F%E4%BA%A2

**Review by zz-jason — COMMENTED** [review]
These two SQLs should both be able to change the global variable. why removing the first one?

**Comment by TomShawn** [comment]
> These two SQLs should both be able to change the global variable. why removing the first one?

The author's description says "修改 global 环境变量的方式，这边在 v3.0.12,v4.0.1测试并不生效，辛苦评估下".

**Comment by glkappe** [comment]
> > These two SQLs should both be able to change the global variable. why removing the first one?
> 
> The author's description says "修改 global 环境变量的方式，这边在 v3.0.12,v4.0.1测试并不生效，辛苦评估下".

@zz-jason  any update?

**Comment by zz-jason** [comment]
@glkappe 
> 去掉 SET @@global.tidb_distsql_scan_concurrency = 10;
> 修改 global 环境变量的方式，这边在 v3.0.12,v4.0.1测试并不生效，辛苦评估下

为什么不生效？

**Comment by glkappe** [comment]
> @glkappe
> 
> > 去掉 SET @@global.tidb_distsql_scan_concurrency = 10;
> > 修改 global 环境变量的方式，这边在 v3.0.12,v4.0.1测试并不生效，辛苦评估下
> 
> 为什么不生效？

The previous test did not take effect, but I don’t know why the test screenshot was not provided. I just tested it and there is no problem. This issue will be closed first.

**Pull request closed without merging**
