### PR TITLE
update comment-syntax.md

### PR DESCRIPTION
**Pull request by tangenta**
### What is changed, added or deleted? (Required)

Update the description of TiDB-specific executable comment syntax.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by ran-huang** [comment]
@tangenta Does this PR apply to v4.0? Please tick the right versions in description.
Also, please involve your team leader as reviewer.

**Comment by tangenta** [comment]
@ran-huang Done.

**Comment by ran-huang** [comment]
@bb7133 PTAL

**Pull request merged**
