### PR TITLE
Remove the description of --sql-mode

### PR DESCRIPTION
**Pull request by glkappe**
Remove the description of --sql-mode

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by glkappe** [comment]
**The --sql-mode parameter was not found in -h, please review the data**


[tidb@node4107 v3.0.12]$ ./tidb-server -V
**Release Version: v3.0.12**
Git Commit Hash: 8c4696b3f3408c61dd7454204ddd67c93501609a
Git Branch: heads/refs/tags/v3.0.12
UTC Build Time: 2020-03-16 09:56:22
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

[tidb@node4107 v3.0.12]$ ./tidb-server -h
Usage of ./tidb-server:
  -L string
        log level: info, debug, warn, error, fatal (default "info")
  -P string
        tidb server port (default "4000")
  -V    print version information and exit (default false)
  -advertise-address string
        tidb server advertise IP
  -check.b
        Run benchmarks
  -check.bmem
        Report memory benchmarks
  -check.btime duration
        approximate run time for each benchmark (default 1s)
  -check.exclude string
        Regular expression to exclude tests to run
  -check.f string
        Regular expression selecting which tests and/or suites to run
  -check.list
        List the names of all tests that will be run
  -check.p
        Run suites in parallel
  -check.v
        Verbose mode
  -check.vv
        Super verbose mode (disables output caching)
  -check.work
        Display and do not remove the test working directory
  -config string
        config file path
  -config-check
        check config file validity and exit (default false)
  -config-strict
        enforce config file validity (default false)
  -cors string
        tidb server allow cors origin
  -enable-binlog
        enable generate binlog (default false)
  -gocheck.b
        Run benchmarks
  -gocheck.btime duration
        approximate run time for each benchmark (default 1s)
  -gocheck.f string
        Regular expression selecting which tests and/or suites to run
  -gocheck.list
        List the names of all tests that will be run
  -gocheck.v
        Verbose mode
  -gocheck.vv
        Super verbose mode (disables output caching)
  -gocheck.work
        Display and do not remove the test working directory
  -host string
        tidb server host (default "0.0.0.0")
  -lease string
        schema lease duration, very dangerous to change only if you know what you do (default "45s")
  -log-file string
        log file path
  -log-slow-query string
        slow query file path
  -metrics-addr string
        prometheus pushgateway address, leaves it empty will disable prometheus push.
  -metrics-interval uint
        prometheus client push interval in second, set "0" to disable prometheus push. (default 15)
  -path string
        tidb storage path (default "/tmp/tidb")
  -plugin-dir string
        the folder that hold plugin (default "/data/deploy/plugin")
  -plugin-load string
        wait load plugin name(separated by comma)
  -proxy-protocol-header-timeout uint
        proxy protocol header read timeout, unit is second. (default 5)
  -proxy-protocol-networks string
        proxy protocol networks allowed IP or *, empty mean disable proxy protocol support
  -record
        to generate test result
  -report-status
        If enable status report HTTP service. (default true)
  -run-ddl
        run ddl worker on this tidb-server (default true)
  -socket string
        The socket file to use for connection.
  -status string
        tidb server status port (default "10080")
  -status-host string
        tidb server status host (default "0.0.0.0")
  -store string
        registered store name, [tikv, mocktikv] (default "mocktikv")
  -token-limit int
        the limit of concurrent executed sessions (default 1000)

**Review by tangenta — APPROVED** [review]

**Pull request merged**
