### PR TITLE
perf-tuning: Add document for topn-limit-push-down (#3307)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3307 to release-3.0

---

### What is changed, added or deleted? (Required)

Add Chinese document for topn-limit-push-down.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [x] v2.1 (TiDB 2.1 versions)

### CODE REVIEW

**Comment by yikeke** [comment]
@LittleFall seems on leave recently. Could you help fix the lint and add this file to TOC.md? @zz-jason

**Comment by LittleFall** [comment]
@yikeke sorry this lint makes me confused.
when I add the slash like `[优化规则及表达式下推的黑名单](/blacklist-control-plan.md)`, it finds a dead link: `/home/circleci/pingcap/docs-cn//blacklist-control-plan.md` as [lint(19480)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6245/workflows/77840b75-8f2b-4385-970c-f76f401fe807/jobs/19480/steps).
when I remove the slash like `[优化规则及表达式下推的黑名单](blacklist-control-plan.md)`, it says `link-must-start-with-slash:blacklist-control-plan.md` as [lint(19479)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6244/workflows/779be960-9dbf-4bec-94ee-2832612da833/jobs/19479/steps).

**Comment by yikeke** [comment]
> @yikeke sorry this lint makes me confused.
> when I add the slash like `[优化规则及表达式下推的黑名单](/blacklist-control-plan.md)`, it finds a dead link: `/home/circleci/pingcap/docs-cn//blacklist-control-plan.md` as [lint(19480)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6245/workflows/77840b75-8f2b-4385-970c-f76f401fe807/jobs/19480/steps).
> when I remove the slash like `[优化规则及表达式下推的黑名单](blacklist-control-plan.md)`, it says `link-must-start-with-slash:blacklist-control-plan.md` as [lint(19479)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6244/workflows/779be960-9dbf-4bec-94ee-2832612da833/jobs/19479/steps).

/blacklist-control-plan.md is the correct format. But because the blacklist-control-plan.md doc has not been merged to release-3.0 branch, so this PR should be merged after https://github.com/pingcap/docs-cn/pull/3760/ merges.

**Comment by yikeke** [comment]
> > @yikeke sorry this lint makes me confused.
> > when I add the slash like `[优化规则及表达式下推的黑名单](/blacklist-control-plan.md)`, it finds a dead link: `/home/circleci/pingcap/docs-cn//blacklist-control-plan.md` as [lint(19480)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6245/workflows/77840b75-8f2b-4385-970c-f76f401fe807/jobs/19480/steps).
> > when I remove the slash like `[优化规则及表达式下推的黑名单](blacklist-control-plan.md)`, it says `link-must-start-with-slash:blacklist-control-plan.md` as [lint(19479)](https://app.circleci.com/pipelines/github/pingcap/docs-cn/6244/workflows/779be960-9dbf-4bec-94ee-2832612da833/jobs/19479/steps).
> 
> /blacklist-control-plan.md is the correct format. But the blacklist-control-plan.md doc has not been merged to release-3.0 branch, so there's this dead link and this PR should be merged after #3760 is merged.

#3760 is merged. Please add this file to TOC.md. @LittleFall

**Pull request merged**
