### PR TITLE
Update check-before-deployment.md

### PR DESCRIPTION
**Pull request by xyqbian**
swapoff -a && swapon -a中将swapon -a删除，因为swapon -a是开启操作
在swap处添加了：可以保证开机后，swap还是关闭状态的
echo "swapoff -a" >>/etc/rc.d/rc.local
chmod +x /etc/rc.d/rc.local
在grubby修改大页处，添加了下面指令，也可以保证重启机器后，大页依旧关闭
echo "echo never > /sys/kernel/mm/transparent_hugepage/defrag" >>/etc/rc.d/rc.local
echo "echo never > /sys/kernel/mm/transparent_hugepage/enabled" >>/etc/rc.d/rc.local
chmod +x /etc/rc.d/rc.local

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by pepezzzz** [comment]
echo "vm.swappiness = 0">> /etc/sysctl.conf 已经保证重启后，swap还是关闭状态的。
参考 https://blog.csdn.net/21cnbao/article/details/79209672

transparent_hugepage=never 加在引导界面后，已经保证重启后，大页依旧关闭，不需要使用 rc.local。
参考 https://www.thegeekdiary.com/centos-rhel-7-how-to-disable-transparent-huge-pages-thp/

**Comment by xyqbian** [comment]
/cc @pepezzzz
您好，我按照官网上修改，第一次使用check脚本是可以：
image
但是我将机器关闭，重启后，再次执行check脚本，swap和thp又不行了
image
然后我将修改信息写入到/etc/rc.local后并且配置执行权限：chmod +x /etc/rc.d/rc.local，后重启执行check脚本也是可以的：
image
image

**Comment by pepezzzz** [comment]
swap 是 tiup check 的问题。
thp 核对有效，过程如下，也有可能是 tiup check 的问题。
[root@host186 ~]# grubby --default-kernel
/boot/vmlinuz-3.10.0-1127.el7.x86_64
[root@host186 ~]# grubby --args="transparent_hugepage=never" --update-kernel `grubby --default-kernel`
[root@host186 ~]# grubby --default-kernel
/boot/vmlinuz-3.10.0-1127.el7.x86_64
[root@host186 ~]# grubby --info `grubby --default-kernel`
index=0
kernel=/boot/vmlinuz-3.10.0-1127.el7.x86_64
args="ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=zh_CN.UTF-8 transparent_hugepage=never"
root=/dev/mapper/centos-root
initrd=/boot/initramfs-3.10.0-1127.el7.x86_64.img
title=CentOS Linux (3.10.0-1127.el7.x86_64) 7 (Core)
[root@host186 ~]# cat /sys/kernel/mm/transparent_hugepage/enabled
[always] madvise never
[root@host186 ~]# reboot

Connection closed by foreign host.

Disconnected from remote host(172.16.5.186) at 20:20:59.

Type `help' to learn how to use Xshell prompt.
[c:\~]$ 

Connecting to 172.16.5.186:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

WARNING! The remote SSH server rejected X11 forwarding request.
Last login: Mon Mar 15 16:30:03 2021 from 192.168.190.100
[root@host186 ~]# cat /sys/kernel/mm/transparent_hugepage/enabled
always madvise [never]
[root@host186 ~]#

**Comment by pepezzzz** [comment]
另外解释一下，为什么推荐用 tuned ，cpupower 等都使用 systemd 服务 ，是因为这种  rc.local 脚本方式不受监控，也不被红帽官方推荐了。

**Comment by xyqcmss** [comment]
/cc @pepezzzz
好的，谢谢，我再看看，辛苦您了！

**Comment by xyqbian** [comment]
/cc @pepezzzz
好的，谢谢，我再看一下，辛苦您了

**Comment by xyqbian** [comment]
ok
I have closed

**Pull request closed without merging**
