### PR TITLE
modify description of tidb_build_stats_concurrency

### PR DESCRIPTION
**Pull request by Jingyuma**
Looks all the columns from each tables will be in one task, and analyze worker handle the taskch.
So if this is correct, the description should change from "每个任务只负责某一个列或者索引" to "每个任务只负责某一个表或者索引".

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by Jingyuma** [comment]
\rebuild

**Comment by TomShawn** [comment]
@Jingyuma 
+ Please involve a technical review.
+ This doc applies to more than dev and v4.0. Please decide whether to modify other applicable versions as well.
+ If this PR applies to both `master` and `release-4.0`, our best practice is to create it based on the `master` branch, **NOT** on the release branch. Remember to create it on `master` next time, thanks~

**Pull request closed without merging**
