### PR TITLE
Update statistics.md

### PR DESCRIPTION
**Pull request by shenzhengcmss**
### What is changed, added or deleted? (Required)

no INDEX will exec failed

### Which TiDB version(s) do your changes apply to? (Required)
master

### CODE REVIEW

**Comment by TomShawn** [comment]
@shenzhengcmss Could you please sign the [CLA](https://cla-assistant.io/pingcap/docs-cn?pullRequest=5762) for this PR to be merged? Thanks~

**Comment by shenzhengcmss** [comment]
@TomShawn why tide is pending

**Comment by TomShawn** [comment]
> @TomShawn why tide is pending

Don't worry. There's nothing wrong with this PR and that does not affect the merge.

**Review by zz-jason — COMMENTED** [review]
LGTM

**Review by winoros — APPROVED** [review]

**Pull request merged**
