### PR TITLE
how-to/deploy: fix the shown Ansible version

### PR DESCRIPTION
**Pull request by superlzs0476**
### What is changed, added or deleted? 

Update the shown Ansible version

### What is the related PR or file link(s)? 

N/A

### Which version does your change affect? 

dev, v3.1, v3.0

### CODE REVIEW

**Comment by superlzs0476** [comment]
@lilin90  @liubo0127  PTAL

**Comment by lilin90** [comment]
@superlzs0476 Do we need to update it in `dev` and `v2.1` too?

**Comment by liubo0127** [comment]
> @superlzs0476 Do we need to update it in `dev` and `v2.1` too?

It can be updated in `dev`, and keep as it is in `v2.1`.

**Comment by lilin90** [comment]
> > @superlzs0476 Do we need to update it in `dev` and `v2.1` too?
> 
> It can be updated in `dev`, and keep as it is in `v2.1`.

Got it.

**Pull request merged**
