### PR TITLE
tools: fix steps of pump deployment

### PR DESCRIPTION
**Pull request by jianhaiqing**
add one more step for pump's deployment.

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by WangXiangUSTC** [comment]
@liubo0127 PTAL

**Comment by WangXiangUSTC** [comment]
same with https://github.com/pingcap/docs-cn/pull/1109

**Comment by lilin90** [comment]
@WangXiangUSTC Then you can close one PR.

**Comment by WangXiangUSTC** [comment]
thanks @jianhaiqing , this pr same with 
https://github.com/pingcap/docs-cn/pull/1109, I will close this one.

**Pull request closed without merging**
