### PR TITLE
sql-statements: add docs for `FETCH FIRST` syntax

### PR DESCRIPTION
**Pull request by time-and-fate**
### What is changed, added or deleted? (Required)

added docs for `FETCH FIRST` syntax

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- Other reference link(s):
master:
https://github.com/pingcap/parser/pull/985
https://github.com/pingcap/tidb/pull/19715
4.0:
https://github.com/pingcap/parser/pull/996
https://github.com/pingcap/tidb/pull/19720

### CODE REVIEW

**Comment by TomShawn** [comment]
@time-and-fate Please involve a technical review.

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
