### PR TITLE
Add TiFlash performance tuning to TOC

### PR DESCRIPTION
**Pull request by JaySon-Huang**
Signed-off-by: JaySon-Huang <tshent@qq.com>

### What is changed, added or deleted? (Required)

Add a doc about how to tune TiFlash performance in TOC.md

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
I found that the english version of TOC.md is not updated to this structure. Will that be updated by docs-refactor members later? @TomShawn

**Comment by TomShawn** [comment]
> I found that the english version of TOC.md is not updated to this structure. Will that be updated by docs-refactor members later? @TomShawn

Yes, the English version of TOC will be updated after the Special Week.

**Comment by yikeke** [comment]
> I found that the english version of TOC.md is not updated to this structure. Will that be updated by docs-refactor members later? @TomShawn

The English version of TOC.md in `docs-special-week`will not be updated this week. If you don't know where to put your new file, please contact me or @lilin90 for more info. @JaySon-Huang

**Comment by TomShawn** [comment]
LGTM

**Pull request merged**
