### PR TITLE
tools: diff add checkpoint config

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
1. add checkpoint config
2. add only-use-checksum config

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@CaitinChen @ericsyh PTAL

**Comment by lilin90** [comment]
@ericsyh PTAL~ Thanks!

**Comment by lilin90** [comment]
@IzabelWang Please help update the corresponding English doc. Thanks!

**Comment by lilin90** [comment]
@WangXiangUSTC Which version does this change affect?

**Comment by WangXiangUSTC** [comment]
@lilin90 v3.0.0-rc3

**Pull request merged**
