### PR TITLE
credits: remove outdated contributor link and repos

### PR DESCRIPTION
**Pull request by lilin90**
c'c

### What is changed, added or deleted? (Required)

- Remove an outdated link of contributors, which does not work now
- Update the list of repos because multiple repos have been combined or migrated to another repo
  - Note: All the changed will be cherry picked to v6.5, v6.6, v7.0 according to the repo archive date, while the change of removing the outdated contributor link will be cherry picked to all selected versions. The docs-dm repo link will be kept for v5.3 and earlier versions.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v7.1 (TiDB 7.1 versions)
- [x] v7.0 (TiDB 7.0 versions)
- [x] v6.6 (TiDB 6.6 versions)
- [x] v6.5 (TiDB 6.5 versions)
- [x] v6.1 (TiDB 6.1 versions)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): 
  - https://github.com/pingcap/dm/pull/2276, https://docs.pingcap.com/zh/tidb-data-migration/v5.3
  - https://github.com/pingcap/br/pull/1421
  - https://github.com/pingcap/tidb-lightning/pull/571
  - https://github.com/pingcap/dumpling/pull/379
  - https://github.com/pingcap/parser/pull/1372

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Comment by lilin90** [comment]
@Oreoxmt Thanks for your review. And I added another commit to remove outdated repo links and added some explanation to the PR description box. PTAL again, thanks!

**Review by Oreoxmt — APPROVED** [review]
LGTM

**Pull request merged**
