### PR TITLE
fix a typo in the SQL example for troubleshoot-write-conflicts.md

### PR DESCRIPTION
**Pull request by hey-hoho**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

fix a typo in the SQL example for troubleshoot-write-conflicts.md
The `table_schema` field should correspond to the `db_name`

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
@hey-hoho Please involve a technical reviewer.

**Comment by hey-hoho** [comment]
> @hey-hoho Please involve a technical reviewer.

right，but which reviewer should I invite?

**Review by TomShawn — APPROVED** [review]

**Review by TomShawn — APPROVED** [review]

**Comment by TomShawn** [comment]
This PR is also approved by @MyonKeminta .

**Review by MyonKeminta — APPROVED** [review]

**Comment by matchge-ca** [comment]
Hey @TomShawn, this typo can also been found on v4.0 and dev branches, can you cherrypick to fix it on those branches? Same typo is also existed on dev, v4.0 and above branches in English docs repo as well.

**Comment by TomShawn** [comment]
> Hey @TomShawn, this typo can also been found on v4.0 and dev branches, can you cherrypick to fix it on those branches? Same typo is also existed on dev, v4.0 and above branches in English docs repo as well.

This PR has been merged into the dev branch, so it is fixed in the dev branch. Recently, the dev version in docs.pingcap.com has stopped updating. Even if the type is fixed in GitHub docs-cn repo, the fixed content will not be displayed on docs.pingcap.com until Nov 23th (preparation for the v5.3 release).

For v4.0 and earlier versions, the product version itself has passed the extended support period. Our support for the documentation of these earlier versions just follows suit. Unless this is a critical typo that causes a serious accident to an important customer who is just using these earlier versions as a high priority issue to fix, we do not fix typos on these earlier versions.

**Pull request merged**
