### PR TITLE
Update optimistic-transaction.md

### PR DESCRIPTION
**Pull request by sylar8023baby**
### What is changed, added or deleted? (Required)

Remove duplicate colon edit descriptor

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

None

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by sylar8023baby** [comment]
/cc @TomShawn

There is a change which need to be reviewed.

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by Liuxiaozhen12** [comment]
There is no duplicate colon in docs so this PR does not need to be translated.
/remove-translation doing
/translation no-need

**Pull request merged**
