### PR TITLE
TiKV configuration: better description for pin-l0-filter-and-index-blocks

### PR DESCRIPTION
**Pull request by yiwu-arbug**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

The description for "pin" l0 index and filter block needs to be more descriptive.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
cc @tabokie

**Review by tabokie — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
Do we want to update for previous versions?  @TomShawn

**Comment by TomShawn** [comment]
> Do we want to update for previous versions (all the way back to v3.0) ? @TomShawn

Now we are adopting a new doc content strategy based on @alex-quan-001 's proposal on documentation.

According to Alex: Once the code is frozen and released as a production version, we should not modify the released code, which is exactly how we should handle user documentation. Once the documentation of a product version is delivered, we should not modify the released documentation, no matter it is about typos, incorrect or inaccurate descriptions. These modifications should be made only on the master branch, the latest development branch, and delivered as document enhancements in the upcoming release versions.

In the light of this proposal, as already announced in an R&D weekly meeting, document enhancements and content fixes will not be cherry-picked to release branches. Only the version-specific content affecting only the current release version (e.g. 5.0.3, 4.0.13, and 5.1.0) are permitted for cherry-pick.

**Comment by yiwu-arbug** [comment]
> > Do we want to update for previous versions (all the way back to v3.0) ? @TomShawn
> 
> Now we are adopting a new doc content strategy based on @alex-quan-001 's proposal on documentation.
> 
> According to Alex: Once the code is frozen and released as a production version, we should not modify the released code, which is exactly how we should handle user documentation. Once the documentation of a product version is delivered, we should not modify the released documentation, no matter it is about typos, incorrect or inaccurate descriptions. These modifications should be made only on the master branch, the latest development branch, and delivered as document enhancements for the upcoming release versions.
> 
> In the light of this proposal, as already announced in an R&D weekly meeting, document enhancements and content fixes will not be cherry-picked to release branches. Only the version-specific content affecting only the current release version (e.g. 5.0.3, 4.0.13, and 5.1.0) are permitted for cherry-pick.

Got it

**Pull request merged**
