### PR TITLE
Update grafana tikv dashboard doc

### PR DESCRIPTION
**Pull request by hunterlxt**
### What is changed, added or deleted? (Required)

The original doc is too old (It may have been two years since the last update), so let's update grafana tikv dashboard doc.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by hunterlxt** [comment]
@Connor1996 Documentation related to rocksdb, titan needs your review. PTAL

**Comment by TomShawn** [comment]
Because this week is Document Special Week, the merge button is temporarily disabled, so we can only merge this PR until the end of the Special Week (presumably this Friday night). Is it acceptable for you? @hunterlxt

**Comment by hunterlxt** [comment]
@TomShawn The task's deadline is today. I think it's better to merge the PR today.

**Comment by TomShawn** [comment]
This is a document update for the Special Week. Please close this PR and create a new one in the `docs-special-week` branch, thanks!

**Pull request closed without merging**
