### PR TITLE
Update post-installation-check.md

### PR DESCRIPTION
**Pull request by mac119**
mysql -u root -h 10.0.1.4 -P 4000 dose not work .  mysql -uroot -h 10.0.1.4 -P 4000  is correct!

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by mac119** [comment]
mysql -u root -h 10.0.1.4 -P 4000 dose not work . mysql -uroot -h 10.0.1.4 -P 4000 is correct!

**Comment by ran-huang** [comment]
@kissmydb PTAL

**Comment by TomShawn** [comment]
@mac119 Thanks for your contribution. Would you sign the [CLA](https://github.com/pingcap/docs-cn/pull/4496#issuecomment-691837016) as requested by CLAassistant for this PR to be merged?

**Comment by TomShawn** [comment]
@mac119 Thanks for your interest in making a contribution to TiDB documentation! As our DBA evaluates, the `mysql -u root -h 10.0.1.4 -P 4000` can work well. Would you provide the error message returned by executing this command?

**Comment by TomShawn** [comment]
@mac119 To better manage the pingcap/docs-cn repo, I'll close this PR for now. If you would like to further work on this PR, you are welcome to reopen it :)

**Pull request closed without merging**
