### PR TITLE
Update mysql-compatibility.md

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What is changed, added or deleted? (Required)
Invisible index is not supported in 4.0

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### CODE REVIEW

**Comment by TomShawn** [comment]
@wjhuang2016 If this PR apply to multiple versions down from `master`, it is recommended to base it on `master` to fully use the cherry-pick feature. Otherwise, we will have to create another PR based on `master`. Also, please involve a technical review.

**Comment by TomShawn** [comment]
@wjhuang2016 Is `master` the only version that supports invisible index?

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Is `master` the only version that supports invisible index?

Yeah.

**Comment by TomShawn** [comment]
@wjhuang2016 What about `不支持 VISIBLE/INVISIBLE 的索引` as written in 3.1/3.0/2.1?
image

**Comment by wjhuang2016** [comment]
> @wjhuang2016 What about `不支持 VISIBLE/INVISIBLE 的索引` as written in 3.1/3.0/2.1?
> image

`Invisible index` is not a common feature. I think I should mention it only if we support it.

**Comment by TomShawn** [comment]
@wjhuang2016 Got it. What about removing this line in 3.1/3.0/2.1?

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Got it. What about removing this line in 3.1/3.0/2.1?

Good idea.

**Pull request merged**
