### PR TITLE
statement-reference: update docs

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
- Update TOC.md
- Update examples of plan binding
- Make clear the scope of Global and Session
- Add a file for `SHOW STATS_HEALTHY`

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/3193; https://github.com/pingcap/docs/pull/3388
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by Joyinqin** [comment]
the dead link can be resolved after https://github.com/pingcap/docs-cn/pull/4313 is merged.

**Comment by TomShawn** [comment]
@lilin90 Please help review this PR, thanks!

**Comment by lilin90** [comment]
@Joyinqin Please fix the lint failure.

**Review by lilin90 — COMMENTED** [review]
LGTM

**Review by lilin90 — APPROVED** [review]

**Review by imtbkcat — APPROVED** [review]
LGTM

**Pull request merged**
