### PR TITLE
Update the default value of joint consensus

### PR DESCRIPTION
**Pull request by qiancai**
### First-time contributors' checklist 

- [] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Update the default value of enable-joint-consensus from false to true for 5.0GA according to the confirmation from Jay

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
Hi @TomShawn  and @BusyJay, I've closed https://github.com/pingcap/docs-cn/pull/5729 which cannot be merged due to CLA issue and commit the changes to this PR, PTAL, thanks.

**Comment by yikeke** [comment]
master 上不用更新吗

**Comment by qiancai** [comment]
> master 上不用更新吗

master 上已经在 v5.0 rc 都时候更新成 true 了

**Pull request merged**
