### PR TITLE
reference: update the descriptions of compability in v3.0.0

### PR DESCRIPTION
**Pull request by winkyao**
### What is changed, added or deleted? 

Update the descriptions of compability.

### Which version does your change affect? 

dev and v3.0

### Checklist 

- [ ] Add a new file to `TOC.md`
- [ ] No Tab spaces anywhere 
- [ ] Leave a blank line both before and after a code block
- [ ] Keep the first level heading consistent with `title` in metadata
- [ ] Use *four* spaces for each level of indentation except that in `TOC.md`

### CODE REVIEW

**Comment by bb7133** [comment]
PTAL @lilin90 , thanks

**Comment by lilin90** [comment]
@TomShawn Please help update it in pingcap/docs. Thanks!

**Comment by TomShawn** [comment]
> @TomShawn Please help update it in pingcap/docs. Thanks!

OK !

**Comment by TomShawn** [comment]
> @TomShawn Please help update it in pingcap/docs. Thanks!

OK !

**Pull request merged**
