### PR TITLE
Changed the alert rule of TiKV_thread_apply_worker_cpu_seconds

### PR DESCRIPTION
**Pull request by hfxsd**
### What is changed, added or deleted? (Required)

Changed the alert rule of `TiKV_thread_apply_worker_cpu_seconds` to the following:

    `max(rate(tikv_thread_cpu_seconds_total{name=~"apply_.*"}[1m])) by (instance) > 0.9`

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):https://github.com/tikv/tikv/issues/11517

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by BusyJay** [comment]
Should wait for https://github.com/tikv/tikv/issues/11517

**Review by BusyJay — APPROVED** [review]

**Review by shichun-0415 — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
> Should wait for [tikv/tikv#11517](https://github.com/tikv/tikv/issues/11517)

Once this PR is ready for merge, please drop a comment in this PR to let us know. Thanks~

**Pull request merged**
