### PR TITLE
tidb-configuration-file: remove allow-auto-random from config manual

### PR DESCRIPTION
**Pull request by tangenta**
### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: N/A
- Other reference link(s): 
  - v4.0: https://github.com/pingcap/tidb/pull/18613
  - master: https://github.com/pingcap/tidb/pull/16596

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by TomShawn** [comment]
是否需要说明 auto random 是默认开启的？

**Comment by wjhuang2016** [comment]
> 是否需要说明 auto random 是默认开启的？

不需要的

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
