### PR TITLE
best-practice: update massive regions to match 4.0

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed, added or deleted? (Required)

Update massive regions to match 4.0.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### CODE REVIEW

**Comment by TomShawn** [comment]
@BusyJay Because this week is Document Special Week, the merge button is temporarily disabled, so we can only merge this PR until the end of the Special Week (presumably this Friday night). Is it acceptable for you?

**Comment by BusyJay** [comment]
I think the failure is not related to the changes.

**Pull request merged**
