### PR TITLE
Fix an image link that causes display failure

### PR DESCRIPTION
**Pull request by lilin90**
### What is changed, added or deleted? (Required)

 Fix the image display issue caused by #4673 
image

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions): will update 4.0 in another PR, including #4673 & this PR
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): #4673

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by ran-huang** [comment]
This image looks a little fuzzy on my screen. Can we provide one with higher resolution?

**Review by ran-huang — APPROVED** [review]

**Comment by lilin90** [comment]
> This image looks a little fuzzy on my screen. Can we provide one with higher resolution?

@ran-huang I've talked this with @TomShawn. @TomShawn Would you please do further improvements when you're available? Thanks!

**Comment by TomShawn** [comment]
> > This image looks a little fuzzy on my screen. Can we provide one with higher resolution?
> 
> @ran-huang I've talked this with @TomShawn. @TomShawn Would you please do further improvements when you're available? Thanks!

Sure. I'll do that.

**Pull request merged**
