### PR TITLE
sql-statements, information-schema: add `END_TIME` field for table `ANALYZE_STATUS`

### PR DESCRIPTION
**Pull request by hidehalo**
### What is changed, added or deleted? 

Add `END_TIME` field for table `ANALYZE_STATUS` which refer to https://github.com/pingcap/tidb/pull/23674

### Which TiDB version(s) do your changes apply to?

- [x] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- https://github.com/pingcap/tidb/pull/23674
- [information-schema-analyze-status](https://docs.pingcap.com/tidb/stable/information-schema-analyze-status)
- [sql-statement-show-analyze-status](https://docs.pingcap.com/tidb/stable/sql-statement-show-analyze-status)

### CODE REVIEW

**Comment by qiancai** [comment]
Hi @hidehalo @winoros @rebelice, we are preparing the user docs for TiDB v5.1 and would like to know whether the doc changes of this PR apply to TiDB v5.1 or not. Would you please check and reply? Thanks!

**Comment by TomShawn** [comment]
@winoros @rebelice Any update?

**Comment by TomShawn** [comment]
@hidehalo @rebelice @winoros we are preparing the user docs for TiDB v5.2 and would like to know whether the doc changes of this PR apply to TiDB v5.2 or not. Would you please check and reply? Thanks!

**Comment by hidehalo** [comment]
> @hidehalo @rebelice @winoros we are preparing the user docs for TiDB v5.2 and would like to know whether the doc changes of this PR apply to TiDB v5.2 or not. Would you please check and reply? Thanks!

Sorry @TomShawn! I'm not work from internal, I have no idea about the release plan. Maybe you can contact @rebelice and @winoros via Slack IM?

**Comment by TomShawn** [comment]
@winoros @rebelice Any update or plan for the feature?

**Pull request closed without merging**
