### PR TITLE
Rename `Duration` to `Time`.

### PR DESCRIPTION
**Pull request by LittleFall**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

TiDB internal code names `Time` as `Duration`, but we shouldn't expose it to users in documents.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): https://github.com/pingcap/parser/blob/master/mysql/type.go#L29-L30

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by TomShawn** [comment]
> /cc @TomShawn Could you help me to solve the check failure?

That doesn't affect PR merge. We can ignore that.

**Review by windtalker — APPROVED** [review]
LGTM

**Review by TomShawn — APPROVED** [review]

**Pull request merged**
