### PR TITLE
op-guide: update ansible-deployment-scale.md

### PR DESCRIPTION
**Pull request by bianxindong**

### CODE REVIEW

**Comment by CaitinChen** [comment]
@bianxindong Thanks for your contribution! ^_^
@LinuxGit PTAL. Thanks.

**Comment by liubo0127** [comment]
The new pd node is indeed supposed to be added in the last line of the pd_servers group.

**Comment by liubo0127** [comment]
@bianxindong 
Hi，you can add note "新增节点 172.16.10.103 应该置于 pd_servers 主机组最后一行。"
at step 1 https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment-scale.md#扩容-pd-节点. 
Then you don't have to add "注意 `run_pd.sh` 中 `--name="pd1" \` 这一配置，name要确认与现有集群配置不同，否则无法join成功。".

**Comment by CaitinChen** [comment]
@liubo0127 PTAL

**Pull request merged**
